# PMBOK 6 Process Agent Types and Dependency Graph

from typing import List, Dict, Any

class PMBOKProcessAgent:
    def __init__(self, code: str, name: str, description: str, inputs: List[str], tools: List[str], outputs: List[str]):
        self.code = code
        self.name = name
        self.description = description
        self.inputs = inputs
        self.tools = tools
        self.outputs = outputs

    async def run(self, data: Any) -> Any:
        # Placeholder for agent logic
        return {"code": self.code, "outputs": self.outputs}

class PMBOKProcessDependency:
    def __init__(self, source: str, target: str, dependency_type: str = "FS", lag_weeks: int = 0):
        self.source = source
        self.target = target
        self.dependency_type = dependency_type
        self.lag_weeks = lag_weeks

# Factory to create all 49 process agents (to be filled with real data)
def create_pmbok_agents() -> Dict[str, PMBOKProcessAgent]:
    agents = {
        "4.1": PMBOKProcessAgent("4.1", "Develop Project Charter", "The process of developing a document that formally authorizes the existence of a project and provides the project manager with the authority to apply organizational resources to project activities.", ["Business documents", "Agreements", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data gathering", "Interpersonal and team skills", "Meetings"], ["Project charter", "Assumptions log"]),
        "4.2": PMBOKProcessAgent("4.2", "Develop Project Management Plan", "The process of defining, preparing, and coordinating all subsidiary plans and integrating them into a comprehensive project management plan. The project management plan defines how the project is executed, monitored and controlled, and closed.", ["Project charter", "Outputs from other processes", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data gathering", "Interpersonal and team skills", "Meetings"], ["Project management plan"]),
        "4.3": PMBOKProcessAgent("4.3", "Direct and Manage Project Work", "The process of leading and performing the work defined in the project management plan and implementing approved changes to achieve the project's objectives.", ["Project management plan", "Project documents", "Approved change requests", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Project management information system", "Meetings"], ["Deliverables", "Work performance data", "Issue log", "Change requests", "Project management plan updates", "Project documents updates"]),
        "4.4": PMBOKProcessAgent("4.4", "Manage Project Knowledge", "The process of using existing knowledge and creating new knowledge to achieve the project's objectives and contribute to organizational learning.", ["Project management plan", "Project documents", "Deliverables", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Knowledge management", "Information management", "Interpersonal and team skills"], ["Lessons learned register", "Project management plan updates", "Organizational process assets updates"]),
        "4.5": PMBOKProcessAgent("4.5", "Monitor and Control Project Work", "The process of tracking, reviewing, and reporting the overall progress to meet the performance objectives defined in the project management plan.", ["Project management plan", "Project documents", "Work performance information", "Agreements", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data analysis", "Decision making", "Meetings"], ["Work performance reports", "Change requests", "Project management plan updates", "Project documents updates"]),
        "4.6": PMBOKProcessAgent("4.6", "Perform Integrated Change Control", "The process of reviewing all change requests, approving changes and managing changes to deliverables, project documents, and the project management plan, and communicating the decisions.", ["Project management plan", "Project documents", "Work performance reports", "Change requests", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Change control tools", "Data analysis", "Decision making", "Meetings"], ["Approved change requests", "Project management plan updates", "Project documents updates"]),
        "4.7": PMBOKProcessAgent("4.7", "Close Project or Phase", "The process of finalizing all activities for the project, phase, or contract.", ["Project charter", "Project management plan", "Project documents", "Accepted deliverables", "Business documents", "Agreements", "Procurement documentation", "Organizational process assets"], ["Expert judgment", "Data analysis", "Meetings"], ["Project documents updates", "Final product, service, or result transition", "Final report", "Organizational process assets updates"]),
        "5.1": PMBOKProcessAgent("5.1", "Plan Scope Management", "The process of creating a scope management plan that documents how the project scope will be defined, validated, and controlled.", ["Project charter", "Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data analysis", "Meetings"], ["Scope management plan", "Requirements management plan"]),
        "5.2": PMBOKProcessAgent("5.2", "Collect Requirements", "The process of determining, documenting, and managing stakeholder needs and requirements to meet project objectives.", ["Project charter", "Project management plan", "Project documents", "Business documents", "Agreements", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data gathering", "Data analysis", "Decision making", "Data representation", "Interpersonal and team skills", "Context diagram", "Prototypes"], ["Requirements documentation", "Requirements traceability matrix"]),
        "5.3": PMBOKProcessAgent("5.3", "Define Scope", "The process of developing a detailed description of the project and product.", ["Project charter", "Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data analysis", "Decision making", "Interpersonal and team skills", "Product analysis"], ["Project scope statement", "Project documents updates"]),
        "5.4": PMBOKProcessAgent("5.4", "Create WBS", "The process of subdividing project deliverables and project work into smaller, more manageable components.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Decomposition"], ["Scope baseline", "Project documents updates"]),
        "5.5": PMBOKProcessAgent("5.5", "Validate Scope", "The process of formalizing acceptance of the completed project deliverables.", ["Project management plan", "Project documents", "Verified deliverables", "Work performance data"], ["Inspection", "Decision making"], ["Accepted deliverables", "Work performance information", "Change requests", "Project documents updates"]),
        "5.6": PMBOKProcessAgent("5.6", "Control Scope", "The process of monitoring the status of the project and product scope and managing changes to the scope baseline.", ["Project management plan", "Project documents", "Work performance data", "Organizational process assets"], ["Data analysis"], ["Work performance information", "Change requests", "Project management plan updates", "Project documents updates"]),
        "6.1": PMBOKProcessAgent("6.1", "Plan Schedule Management", "The process of establishing the policies, procedures, and documentation for planning, developing, managing, executing, and controlling the project schedule.", ["Project charter", "Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data analysis", "Meetings"], ["Schedule management plan"]),
        "6.2": PMBOKProcessAgent("6.2", "Define Activities", "The process of identifying and documenting the specific actions to be performed to produce the project deliverables.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Decomposition", "Rolling wave planning", "Meetings"], ["Activity list", "Activity attributes", "Milestone list", "Change requests", "Project management plan updates"]),
        "6.3": PMBOKProcessAgent("6.3", "Sequence Activities", "The process of identifying and documenting relationships among the project activities.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Precedence diagramming method", "Dependency determination and integration", "Leads and lags", "Project management information system"], ["Project schedule network diagrams", "Project documents updates"]),
        "6.4": PMBOKProcessAgent("6.4", "Estimate Activity Durations", "The process of estimating the number of work periods needed to complete individual activities with estimated resources.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Analogous estimating", "Parametric estimating", "Three-point estimating", "Bottom-up estimating", "Data analysis", "Decision making", "Meetings"], ["Duration estimates", "Basis of estimates", "Project documents updates"]),
        "6.5": PMBOKProcessAgent("6.5", "Develop Schedule", "The process of analyzing activity sequences, durations, resource requirements, and schedule constraints to create the project schedule model.", ["Project management plan", "Project documents", "Agreements", "Enterprise environmental factors", "Organizational process assets"], ["Schedule network analysis", "Critical path method", "Resource optimization", "Data analysis", "Leads and lags", "Schedule compression", "Project management information system", "Agile release planning"], ["Schedule baseline", "Project schedule", "Schedule data", "Project calendars", "Change requests", "Project management plan updates", "Project documents updates"]),
        "6.6": PMBOKProcessAgent("6.6", "Control Schedule", "The process of monitoring the status of project activities to update project progress and manage changes to the schedule baseline to achieve the plan.", ["Project management plan", "Project documents", "Work performance data", "Organizational process assets"], ["Data analysis", "Critical path method", "Project management information system", "Resource optimization", "Leads and lags", "Schedule compression"], ["Work performance information", "Schedule forecasts", "Change requests", "Project management plan updates", "Project documents updates"]),
        "7.1": PMBOKProcessAgent("7.1", "Plan Cost Management", "The process of defining how the project costs will be estimated, budgeted, managed, monitored, and controlled.", ["Project charter", "Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data analysis", "Meetings"], ["Cost management plan"]),
        "7.2": PMBOKProcessAgent("7.2", "Estimate Costs", "The process of developing an approximation of the monetary resources needed to complete project work.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Analogous estimating", "Parametric estimating", "Bottom-up estimating", "Three-point estimating", "Data analysis", "Project management information system", "Decision making"], ["Cost estimates", "Basis of estimates", "Project documents updates"]),
        "7.3": PMBOKProcessAgent("7.3", "Determine Budget", "The process of aggregating the estimated costs of individual activities or work packages to establish an authorized cost baseline.", ["Project management plan", "Project documents", "Business documents", "Agreements", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Cost aggregation", "Data analysis", "Historical information review", "Funding limit reconciliation", "Financing"], ["Cost baseline", "Project funding requirements", "Project documents updates"]),
        "7.4": PMBOKProcessAgent("7.4", "Control Costs", "The process of monitoring the status of the project to update the project costs and managing changes to the cost baseline.", ["Project management plan", "Project documents", "Project funding requirements", "Work performance data", "Organizational process assets"], ["Expert judgment", "Data analysis", "To-complete performance index", "Project management information system"], ["Work performance information", "Cost forecasts", "Change requests", "Project management plan updates", "Project documents updates"]),
        "8.1": PMBOKProcessAgent("8.1", "Plan Quality Management", "The process of identifying quality requirements and/or standards for the project and its deliverables and documenting how the project will demonstrate compliance with quality requirements.", ["Project charter", "Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data gathering", "Data analysis", "Decision making", "Data representation", "Test and inspection planning", "Meetings"], ["Quality management plan", "Quality metrics", "Project management plan updates", "Project documents updates"]),
        "8.2": PMBOKProcessAgent("8.2", "Manage Quality", "The process of translating the quality management plan into executable quality activities that incorporate the organization's quality policies into the project.", ["Project management plan", "Project documents", "Organizational process assets"], ["Data gathering", "Data analysis", "Decision making", "Data representation", "Audits", "Design for X", "Problem solving", "Quality improvement methods"], ["Quality reports", "Test and evaluation documents", "Change requests", "Project management plan updates", "Project documents updates"]),
        "8.3": PMBOKProcessAgent("8.3", "Control Quality", "The process of monitoring and recording results of executing the quality management activities to assess performance and ensure the project outputs are complete, correct, and meet customer expectations.", ["Project management plan", "Project documents", "Approved change requests", "Deliverables", "Work performance data", "Enterprise environmental factors", "Organizational process assets"], ["Data gathering", "Data analysis", "Inspection", "Testing/product evaluations", "Data representation", "Meetings"], ["Quality control measurements", "Verified deliverables", "Work performance information", "Change requests", "Project management plan updates", "Project documents updates"]),
        "9.1": PMBOKProcessAgent("9.1", "Plan Resource Management", "The process of defining how to estimate, acquire, manage, and utilize physical and team resources.", ["Project charter", "Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data representation", "Organizational theory", "Meetings"], ["Resource management plan", "Team charter", "Project documents updates"]),
        "9.2": PMBOKProcessAgent("9.2", "Estimate Activity Resources", "The process of estimating team resources and the type and quantities of materials, equipment, and supplies necessary to perform project work.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Bottom-up estimating", "Analogous estimating", "Parametric estimating", "Data analysis", "Project management information system", "Meetings"], ["Resource requirements", "Basis of estimates", "Resource breakdown structure", "Project documents updates"]),
        "9.3": PMBOKProcessAgent("9.3", "Acquire Resources", "The process of obtaining team members, facilities, equipment, materials, supplies, and other resources necessary to complete project work.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Decision making", "Interpersonal and team skills", "Pre-assignment", "Virtual teams", "Negotiation", "Acquisition"], ["Physical resource assignments", "Project team assignments", "Resource calendars", "Change requests", "Project management plan updates", "Project documents updates", "Enterprise environmental factors updates", "Organizational process assets updates"]),
        "9.4": PMBOKProcessAgent("9.4", "Develop Team", "The process of improving competencies, team member interaction, and the overall team environment to enhance project performance.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Colocation", "Virtual teams", "Communication technology", "Interpersonal and team skills", "Recognition and rewards", "Training", "Individual and team assessments", "Meetings"], ["Team performance assessments", "Change requests", "Project management plan updates", "Project documents updates", "Enterprise environmental factors updates", "Organizational process assets updates"]),
        "9.5": PMBOKProcessAgent("9.5", "Manage Team", "The process of tracking team member performance, providing feedback, resolving issues, and managing team changes to optimize project performance.", ["Project management plan", "Project documents", "Work performance reports", "Team performance assessments", "Enterprise environmental factors", "Organizational process assets"], ["Interpersonal and team skills", "Project management information system"], ["Change requests", "Project management plan updates", "Project documents updates", "Enterprise environmental factors updates"]),
        "9.6": PMBOKProcessAgent("9.6", "Control Resources", "The process of ensuring that the physical resources assigned and allocated to the project are available as planned, as well as monitoring the planned versus actual use of resources, and performing corrective action as necessary.", ["Project management plan", "Project documents", "Work performance data", "Agreements", "Organizational process assets"], ["Data analysis", "Problem solving", "Interpersonal and team skills", "Project management information system"], ["Work performance information", "Change requests", "Project management plan updates", "Project documents updates"]),
        "10.1": PMBOKProcessAgent("10.1", "Plan Communications Management", "The process of developing an appropriate approach and plan for project communications based on stakeholder's information needs and requirements, and available organizational assets.", ["Project charter", "Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Communication requirements analysis", "Communication technology", "Communication models", "Communication methods", "Interpersonal and team skills", "Data representation", "Meetings"], ["Communications management plan", "Project management plan updates", "Project documents updates"]),
        "10.2": PMBOKProcessAgent("10.2", "Manage Communications", "The process of ensuring timely and appropriate collection, creation, distribution, storage, retrieval, management, monitoring, and the ultimate disposition of project information.", ["Project management plan", "Project documents", "Work performance reports", "Enterprise environmental factors", "Organizational process assets"], ["Communication technology", "Communication methods", "Communication skills", "Project management information system", "Project reporting", "Interpersonal and team skills", "Meetings"], ["Project communications", "Project management plan updates", "Project documents updates", "Organizational process assets updates"]),
        "10.3": PMBOKProcessAgent("10.3", "Monitor Communications", "The process of ensuring the information needs of the project and its stakeholders are met.", ["Project management plan", "Project documents", "Work performance data", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Project management information system", "Data representation", "Interpersonal and team skills", "Meetings"], ["Work performance information", "Change requests", "Project management plan updates", "Project documents updates"]),
        "11.1": PMBOKProcessAgent("11.1", "Plan Risk Management", "The process of defining how to conduct risk management activities for a project.", ["Project charter", "Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data analysis", "Meetings"], ["Risk management plan"]),
        "11.2": PMBOKProcessAgent("11.2", "Identify Risks", "The process of identifying individual project risks as well as sources of overall project risk and documenting their characteristics.", ["Project management plan", "Project documents", "Agreements", "Procurement documentation", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data gathering", "Data analysis", "Interpersonal and team skills", "Prompt lists", "Meetings"], ["Risk register", "Risk report", "Project documents updates"]),
        "11.3": PMBOKProcessAgent("11.3", "Perform Qualitative Risk Analysis", "The process of prioritizing individual project risks for further analysis or action by assessing their probability of occurrence and impact as well as other characteristics.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data gathering", "Data analysis", "Interpersonal and team skills", "Risk data quality assessment", "Risk categorization", "Data representation", "Meetings"], ["Project documents updates"]),
        "11.4": PMBOKProcessAgent("11.4", "Perform Quantitative Risk Analysis", "The process of numerically analyzing the combined effect of identified individual project risks and other sources of uncertainty on overall project objectives.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data gathering", "Interpersonal and team skills", "Representations of uncertainty", "Data analysis"], ["Project documents updates"]),
        "11.5": PMBOKProcessAgent("11.5", "Plan Risk Responses", "The process of developing options, selecting strategies, and agreeing on actions to address overall project risk exposure, as well as to treat individual project risks.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data gathering", "Interpersonal and team skills", "Strategies for threats", "Strategies for opportunities", "Contingent response strategies", "Data analysis", "Decision making"], ["Change requests", "Project management plan updates", "Project documents updates"]),
        "11.6": PMBOKProcessAgent("11.6", "Implement Risk Responses", "The process of implementing agreed-upon risk response plans.", ["Project management plan", "Project documents", "Organizational process assets"], ["Expert judgment", "Interpersonal and team skills", "Project management information system"], ["Change requests", "Project documents updates"]),
        "11.7": PMBOKProcessAgent("11.7", "Monitor Risks", "The process of monitoring the implementation of agreed-upon risk response plans, tracking identified risks, identifying and analyzing new risks, and evaluating risk process effectiveness throughout the project.", ["Project management plan", "Project documents", "Work performance data", "Work performance reports"], ["Data analysis", "Audits", "Meetings"], ["Work performance information", "Change requests", "Project management plan updates", "Project documents updates", "Organizational process assets updates"]),
        "12.1": PMBOKProcessAgent("12.1", "Plan Procurement Management", "The process of documenting project procurement decisions, specifying the approach, and identifying potential sellers.", ["Project charter", "Business documents", "Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data gathering", "Data analysis", "Source selection analysis", "Meetings"], ["Procurement management plan", "Procurement strategy", "Bid documents", "Procurement statement of work", "Source selection criteria", "Make-or-buy decisions", "Independent cost estimates", "Change requests", "Project documents updates"]),
        "12.2": PMBOKProcessAgent("12.2", "Conduct Procurements", "The process of obtaining seller responses, selecting a seller, and awarding a contract.", ["Project management plan", "Project documents", "Procurement documentation", "Seller proposals", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Advertising", "Bidder conferences", "Data analysis", "Interpersonal and team skills"], ["Selected sellers", "Agreements", "Change requests", "Project management plan updates", "Project documents updates"]),
        "12.3": PMBOKProcessAgent("12.3", "Control Procurements", "The process of managing procurement relationships, monitoring contract performance, making changes and corrections as appropriate, and closing out contracts.", ["Project management plan", "Project documents", "Agreements", "Procurement documentation", "Approved change requests", "Work performance data", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Claims administration", "Data analysis", "Inspection", "Audits"], ["Closed procurements", "Work performance information", "Procurement documentation updates", "Change requests", "Project management plan updates", "Project documents updates", "Organizational process assets updates"]),
        "13.1": PMBOKProcessAgent("13.1", "Identify Stakeholders", "The process of identifying project stakeholders regularly and analyzing and documenting relevant information regarding their interests, involvement, interdependencies, influence, and potential impact on project success.", ["Project charter", "Business documents", "Project management plan", "Project documents", "Agreements", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data gathering", "Data analysis", "Data representation", "Meetings"], ["Stakeholder register", "Change requests", "Project management plan updates"]),
        "13.2": PMBOKProcessAgent("13.2", "Plan Stakeholder Engagement", "The process of developing approaches to involve project stakeholders based on their needs, expectations, interests, and potential impact on the project.", ["Project charter", "Project management plan", "Project documents", "Agreements", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Data gathering", "Data analysis", "Decision making", "Data representation", "Meetings"], ["Stakeholder engagement plan"]),
        "13.3": PMBOKProcessAgent("13.3", "Manage Stakeholder Engagement", "The process of communicating and working with stakeholders to meet their needs and expectations, address issues, and foster appropriate stakeholder engagement involvement.", ["Project management plan", "Project documents", "Enterprise environmental factors", "Organizational process assets"], ["Expert judgment", "Communication skills", "Interpersonal and team skills", "Ground rules", "Meetings"], ["Change requests", "Project management plan updates", "Project documents updates"]),
        "13.4": PMBOKProcessAgent("13.4", "Monitor Stakeholder Engagement", "The process of monitoring overall project stakeholder relationships and tailoring strategies for engaging stakeholders through the modification of engagement strategies and plans.", ["Project management plan", "Project documents", "Work performance data", "Enterprise environmental factors", "Organizational process assets"], ["Data analysis", "Decision making", "Data representation", "Communication skills", "Interpersonal and team skills", "Meetings"], ["Work performance information", "Change requests", "Project management plan updates", "Project documents updates"]),
    }
    return agents

# Dependency list (from provided table)
PMBOK_DEPENDENCIES: List[PMBOKProcessDependency] = [
    PMBOKProcessDependency("4.1", "13.1"),
    PMBOKProcessDependency("4.1", "4.2"),
    PMBOKProcessDependency("13.1", "13.2"),
    PMBOKProcessDependency("4.2", "5.1"),
    PMBOKProcessDependency("5.1", "5.2"),
    PMBOKProcessDependency("5.2", "5.3"),
    PMBOKProcessDependency("5.3", "5.4"),
    PMBOKProcessDependency("4.2", "6.1"),
    PMBOKProcessDependency("5.4", "6.2"),
    PMBOKProcessDependency("6.2", "6.3"),
    PMBOKProcessDependency("6.3", "6.4"),
    PMBOKProcessDependency("6.4", "6.5"),
    PMBOKProcessDependency("4.2", "7.1"),
    PMBOKProcessDependency("6.5", "7.2"),
    PMBOKProcessDependency("7.2", "7.3"),
    PMBOKProcessDependency("4.2", "8.1"),
    PMBOKProcessDependency("4.2", "9.1"),
    PMBOKProcessDependency("9.1", "9.2"),
    PMBOKProcessDependency("9.1", "9.3"),
    PMBOKProcessDependency("9.3", "9.4"),
    PMBOKProcessDependency("9.4", "9.5"),
    PMBOKProcessDependency("4.2", "10.1"),
    PMBOKProcessDependency("4.2", "11.1"),
    PMBOKProcessDependency("11.1", "11.2"),
    PMBOKProcessDependency("11.2", "11.3"),
    PMBOKProcessDependency("11.3", "11.4"),
    PMBOKProcessDependency("11.4", "11.5"),
    PMBOKProcessDependency("11.5", "11.6"),
    PMBOKProcessDependency("11.6", "11.7"),
    PMBOKProcessDependency("4.2", "12.1"),
    PMBOKProcessDependency("4.2", "4.3"),
    PMBOKProcessDependency("4.2", "4.4"),
    PMBOKProcessDependency("8.1", "8.2"),
    PMBOKProcessDependency("8.2", "8.3"),
    PMBOKProcessDependency("9.5", "9.6"),
    PMBOKProcessDependency("10.2", "10.3"),
    PMBOKProcessDependency("11.6", "11.7"),
    PMBOKProcessDependency("12.2", "12.3"),
    PMBOKProcessDependency("13.3", "13.4"),
    PMBOKProcessDependency("4.2", "4.5"),
    PMBOKProcessDependency("5.4", "5.5"),
    PMBOKProcessDependency("5.3", "5.6"),
    PMBOKProcessDependency("6.5", "6.6"),
    PMBOKProcessDependency("7.3", "7.4"),
    PMBOKProcessDependency("8.2", "8.3"),
    PMBOKProcessDependency("9.5", "9.6"),
    PMBOKProcessDependency("10.2", "10.3"),
    PMBOKProcessDependency("11.6", "11.7"),
    PMBOKProcessDependency("12.2", "12.3"),
    PMBOKProcessDependency("13.3", "13.4"),
    PMBOKProcessDependency("4.5", "4.6"),
    PMBOKProcessDependency("5.4", "5.5"),
    PMBOKProcessDependency("5.5", "4.7"),
    PMBOKProcessDependency("12.3", "4.7"),
]
