// <auto-generated />
using System;
using System.Collections.Generic;
using Adpa.Orchestrator.Data;
using Adpa.Orchestrator.Models.Rituals;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adpa.Orchestrator.Migrations
{
    [DbContext(typeof(GovernanceDbContext))]
    [Migration("20260412201734_AddMsrfPersistence")]
    partial class AddMsrfPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adpa.Orchestrator.Models.Rituals.BusinessCase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasJsonPropertyName("id");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("approval_status");

                    b.PrimitiveCollection<string>("CoreRequirements")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("core_requirements");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<List<CostItem>>("EstimatedCosts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("estimated_costs");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("executive_summary");

                    b.PrimitiveCollection<string>("ExpectedBenefits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("expected_benefits");

                    b.Property<string>("IdeationSummaryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("ideation_summary_id");

                    b.PrimitiveCollection<string>("KeyRisks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("key_risks");

                    b.PrimitiveCollection<string>("Placeholders")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("placeholders");

                    b.Property<string>("ProblemStatement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("problem_statement");

                    b.Property<string>("ProposedSolution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("proposed_solution");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("recommendation");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.ToTable("BusinessCases");
                });

            modelBuilder.Entity("Adpa.Orchestrator.Models.Rituals.IdeationSummary", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasJsonPropertyName("title");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("approval_status");

                    b.PrimitiveCollection<string>("Assumptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("assumptions");

                    b.Property<List<Conflict>>("Conflicts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("conflicts");

                    b.PrimitiveCollection<string>("Constraints")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("constraints");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasJsonPropertyName("id");

                    b.PrimitiveCollection<string>("KeyGoals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("key_goals");

                    b.Property<string>("ProblemStatement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("problem_statement");

                    b.Property<string>("ProposedSolution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("proposed_solution");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("session_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("version");

                    b.HasKey("Title");

                    b.ToTable("IdeationSummaries");
                });

            modelBuilder.Entity("Adpa.Orchestrator.Models.Rituals.MsrfEvaluation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasJsonPropertyName("id");

                    b.Property<string>("EvaluatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("evaluated_at");

                    b.Property<bool>("IsMsrfValidated")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("is_msrf_validated");

                    b.Property<double>("OverallComplianceScore")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("overall_compliance_score");

                    b.Property<List<PillarScore>>("PillarScores")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("pillar_scores");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("project_id");

                    b.PrimitiveCollection<string>("RemediationInstructions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("remediation_instructions");

                    b.Property<double>("StabilityScore")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("stability_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("status");

                    b.HasKey("Id");

                    b.ToTable("msrf_evaluations", (string)null);
                });

            modelBuilder.Entity("Adpa.Orchestrator.Models.Rituals.RtmAmendment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasJsonPropertyName("id");

                    b.Property<string>("AmendmentSubType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("amendment_sub_type");

                    b.Property<string>("AmendmentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("amendment_type");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("applied_at");

                    b.Property<string>("AppliedBy")
                        .HasColumnType("text")
                        .HasJsonPropertyName("applied_by");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("approval_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasColumnType("text")
                        .HasJsonPropertyName("decided_by");

                    b.Property<string>("DecisionNotes")
                        .HasColumnType("text")
                        .HasJsonPropertyName("decision_notes");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("justification");

                    b.Property<string>("OriginalDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("original_description");

                    b.Property<string>("ProposedDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("proposed_description");

                    b.Property<string>("Requester")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("requester");

                    b.Property<string>("ResultingRequirementId")
                        .HasColumnType("text")
                        .HasJsonPropertyName("resulting_requirement_id");

                    b.Property<int>("SourceVersion")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("source_version");

                    b.Property<string>("TargetRequirementId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("target_requirement_id");

                    b.HasKey("Id");

                    b.ToTable("rtm_amendments", (string)null);
                });

            modelBuilder.Entity("Adpa.Orchestrator.Models.Rituals.RtmRequirement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasJsonPropertyName("id");

                    b.Property<string>("AmendmentId")
                        .HasColumnType("text")
                        .HasJsonPropertyName("amendment_id");

                    b.Property<string>("BusinessCaseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("business_case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("CsrVersion")
                        .HasColumnType("text")
                        .HasJsonPropertyName("csr_version");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("domain");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("executed_at");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("priority");

                    b.Property<int>("SourceVersion")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("source_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("status");

                    b.HasKey("Id");

                    b.ToTable("requirements_traceability_matrix", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
