-- Migration 426: IP Claims & Governance Tables
-- RPAS-CM-ENV-IP-001 — IP Novelty Assessment Pipeline
-- Creates ip_claims, ip_claim_entities, and seeds ip_novelty_review approval workflow

-- ============================================================================
-- TABLE: ip_claims
-- ============================================================================

CREATE TABLE IF NOT EXISTS ip_claims (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id                UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  drift_record_id           UUID REFERENCES baseline_drift_detection(id) ON DELETE SET NULL,
  source_entity_ids         UUID[]                                    DEFAULT '{}',
  source_document_ids       UUID[]                                    DEFAULT '{}',
  novelty_score             DECIMAL(3,2) CHECK (novelty_score BETWEEN 0 AND 1),
  ip_classification         TEXT CHECK (ip_classification IN ('patent', 'copyright', 'trade_secret', 'none')),
  prior_art_found           BOOLEAN                                   DEFAULT FALSE,
  system_origin_verified    BOOLEAN                                   DEFAULT FALSE,
  legal_review_status       TEXT                                      DEFAULT 'pending'
                              CHECK (legal_review_status IN ('pending', 'approved', 'rejected', 'investigating')),
  legal_reviewer_id         UUID REFERENCES users(id) ON DELETE SET NULL,
  filing_status             TEXT                                      DEFAULT 'draft'
                              CHECK (filing_status IN (
                                'draft', 'filed', 'pending_examination',
                                'granted', 'rejected', 'appealed', 'trade_secret_registered'
                              )),
  target_agency             TEXT CHECK (target_agency IN ('USPTO', 'EPO', 'WIPO', 'COPYRIGHT', 'INTERNAL')),
  agency_reference_number   TEXT,
  estimated_ip_value        DECIMAL(15,2)                             DEFAULT 0,
  evidence_document_id      UUID REFERENCES documents(id) ON DELETE SET NULL,
  filing_document_id        UUID REFERENCES documents(id) ON DELETE SET NULL,
  filed_at                  TIMESTAMPTZ,
  granted_at                TIMESTAMPTZ,
  next_maintenance_due      TIMESTAMPTZ,
  created_at                TIMESTAMPTZ                               DEFAULT NOW(),
  updated_at                TIMESTAMPTZ                               DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ip_claims_project_id       ON ip_claims(project_id);
CREATE INDEX IF NOT EXISTS idx_ip_claims_drift_record_id  ON ip_claims(drift_record_id);
CREATE INDEX IF NOT EXISTS idx_ip_claims_legal_status     ON ip_claims(legal_review_status);
CREATE INDEX IF NOT EXISTS idx_ip_claims_filing_status    ON ip_claims(filing_status);
CREATE INDEX IF NOT EXISTS idx_ip_claims_classification   ON ip_claims(ip_classification);

COMMENT ON TABLE ip_claims IS 'Tracks IP novelty claims generated by the ADPA IP Governance Pipeline (RPAS-CM-ENV-IP-001)';

-- ============================================================================
-- TABLE: ip_claim_entities (entity provenance links)
-- ============================================================================

CREATE TABLE IF NOT EXISTS ip_claim_entities (
  ip_claim_id   UUID REFERENCES ip_claims(id) ON DELETE CASCADE,
  entity_id     UUID NOT NULL,
  entity_role   TEXT NOT NULL CHECK (entity_role IN ('primary_invention', 'supporting_evidence', 'prior_art_reference')),
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (ip_claim_id, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_ip_claim_entities_entity_id ON ip_claim_entities(entity_id);

-- ============================================================================
-- APPROVAL WORKFLOW SEED: ip_novelty_review
-- Adds the workflow row required by approvalWorkflowService.findWorkflow()
-- Only inserts if it doesn't already exist
-- ============================================================================

INSERT INTO approval_workflows (
  name,
  description,
  workflow_type,
  routing_rules,
  approval_stages,
  sla_hours,
  critical_sla_hours,
  escalation_enabled,
  escalation_after_hours,
  escalation_to,
  notification_channels,
  is_active
)
SELECT
  'IP Novelty Review Workflow',
  'Legal team review workflow for intellectual property claims detected from innovation drift (RPAS-CM-ENV-IP-001)',
  'ip_novelty_review',
  '{"route_to": "legal_reviewer", "cc": ["admin"], "require_all": true}'::jsonb,
  '[{"stage": 1, "role": "legal_reviewer", "required": true}]'::jsonb,
  240,    -- 10 business days
  480,    -- 20 business days critical path
  true,
  200,    -- Escalate after ~8 business days
  ARRAY['admin'],
  ARRAY['email', 'dashboard'],
  true
WHERE NOT EXISTS (
  SELECT 1 FROM approval_workflows WHERE workflow_type = 'ip_novelty_review'
);

-- ============================================================================
-- AUTO-UPDATE TRIGGER for ip_claims.updated_at
-- ============================================================================

CREATE OR REPLACE FUNCTION update_ip_claims_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ip_claims_updated_at ON ip_claims;
CREATE TRIGGER trg_ip_claims_updated_at
  BEFORE UPDATE ON ip_claims
  FOR EACH ROW EXECUTE FUNCTION update_ip_claims_updated_at();
