-- Migration: Add Template Paragraphs Field to Templates Table
-- Description: Adds template_paragraphs field to define expected sections/paragraphs to be generated
-- Date: 2025-01-05
-- Version: 1.0.0

-- Add template_paragraphs column to templates table
ALTER TABLE templates 
ADD COLUMN IF NOT EXISTS template_paragraphs JSONB;

-- Add index for better performance on template_paragraphs field
CREATE INDEX IF NOT EXISTS idx_templates_template_paragraphs 
ON templates USING GIN (template_paragraphs);

-- Add comment to document the new field
COMMENT ON COLUMN templates.template_paragraphs IS 'Expected sections/paragraphs to be generated by the AI provider for this template';

-- Create a function to validate template paragraphs configuration
CREATE OR REPLACE FUNCTION validate_template_paragraphs_config(paragraphs JSONB)
RETURNS BOOLEAN AS $$
DECLARE
    paragraph JSONB;
BEGIN
    -- Check if paragraphs is valid JSONB
    IF paragraphs IS NULL THEN
        RETURN true; -- NULL is allowed (no specific paragraphs defined)
    END IF;
    
    -- Check paragraphs is an array
    IF jsonb_typeof(paragraphs) != 'array' THEN
        RETURN false;
    END IF;
    
    -- Validate each paragraph
    FOR paragraph IN SELECT jsonb_array_elements(paragraphs)
    LOOP
        -- Check required paragraph fields
        IF NOT (paragraph ? 'section_name' AND paragraph ? 'section_type' AND paragraph ? 'description') THEN
            RETURN false;
        END IF;
        
        -- Check section type is valid
        IF NOT (paragraph->>'section_type' IN ('header', 'paragraph', 'list', 'table', 'code_block', 'summary', 'conclusion')) THEN
            RETURN false;
        END IF;
    END LOOP;
    
    RETURN true;
END;
$$ LANGUAGE plpgsql;

-- Add check constraint to validate the template paragraphs configuration
ALTER TABLE templates 
ADD CONSTRAINT chk_templates_template_paragraphs 
CHECK (validate_template_paragraphs_config(template_paragraphs));

-- Update existing templates with sample template paragraphs
UPDATE templates 
SET template_paragraphs = jsonb_build_array(
    jsonb_build_object(
        'section_name', 'Executive Summary',
        'section_type', 'summary',
        'description', 'High-level overview of the project and key outcomes',
        'required', true,
        'order', 1
    ),
    jsonb_build_object(
        'section_name', 'Project Overview',
        'section_type', 'paragraph',
        'description', 'Detailed description of the project scope and objectives',
        'required', true,
        'order', 2
    ),
    jsonb_build_object(
        'section_name', 'Key Deliverables',
        'section_type', 'list',
        'description', 'List of major deliverables and milestones',
        'required', true,
        'order', 3
    )
)
WHERE template_paragraphs IS NULL AND category = 'Project Management Plans';

-- Create a view for templates with all AI enhancements
CREATE OR REPLACE VIEW templates_with_full_ai_enhancements AS
SELECT 
    t.*,
    CASE 
        WHEN t.system_prompt IS NOT NULL AND t.system_prompt != '' THEN true 
        ELSE false 
    END as has_system_prompt,
    CASE 
        WHEN t.context_injection_config->>'enabled' = 'true' THEN true 
        ELSE false 
    END as context_injection_enabled,
    CASE 
        WHEN t.prompt_build_up->>'enabled' = 'true' THEN true 
        ELSE false 
    END as prompt_build_up_enabled,
    CASE 
        WHEN t.template_paragraphs IS NOT NULL AND jsonb_array_length(t.template_paragraphs) > 0 THEN true 
        ELSE false 
    END as has_template_paragraphs,
    jsonb_array_length(t.context_injection_config->'sources') as context_sources_count,
    jsonb_array_length(t.prompt_build_up->'stages') as prompt_stages_count,
    jsonb_array_length(t.template_paragraphs) as template_paragraphs_count
FROM templates t
WHERE t.deleted_at IS NULL;

-- Grant permissions on the view
GRANT SELECT ON templates_with_full_ai_enhancements TO authenticated_users;
