import { 
  AgentDefinition, 
  AgentRelationship, 
  SemanticKnowledgeBase, 
  RegistryPolicy 
} from '../../types/agents';

export const AGENT_SEED_DATA = {
  agents: [
    {
      agent_id: 'AGT-PM-001',
      role_id: 'ROLE-PROJECT_MANAGER',
      name: 'Project Manager Agent',
      classification: { domain: 'Project Management', tier: 'Governance-T2', criticality: 'High' },
      authority: {
        standards: ['PMBOK-8', 'ISO-21500'],
        decision_scope: ['Plan Approval', 'Scope Validation'],
        escalation_path: ['AGT-PMO-HEAD'],
      },
      responsibilities: [
        { id: 'RESP-001', description: 'Validate project plans', success_criteria: ['Completeness ≥ 95%', 'Dependency alignment verified'] },
        { id: 'RESP-002', description: 'Manage risk register' },
      ],
      capabilities: ['Plan Evaluation', 'Risk Scoring', 'Dependency Analysis'],
      inputs: { required: ['TASK_METADATA', 'PROJECT_CHARTER', 'DEPENDENCY_GRAPH'], optional: ['HISTORICAL_PROJECT_DATA'] },
      outputs: [{ type: 'DECISION', format: 'STRUCTURED_JSON' }, { type: 'VALIDATION_REPORT', format: 'AUDIT_LOG' }],
      execution: { mode: 'DETERMINISTIC', retry_policy: { retries: 2, condition: 'VALIDATION_FAILURE' } },
      rules: { validation_rules: [{ id: 'VAL-001', description: 'Plan must cover all PMBOK domains' }, { id: 'VAL-002', description: 'Risk register must exist' }] },
      knowledge_base: {
        skb_id: 'SKB-PM-CORE',
        layers: { ontology: 'ONT-PM-V1', authority_sources: ['PMBOK-8', 'ISO-21500'], evidence: ['REGISTRY_ARTIFACTS'], execution_assets: ['PLAN_TEMPLATES', 'VALIDATION_RULESETS'] },
      },
      context_policy: { isolation_level: 'ROLE_SCOPED', shared_context_access: ['GLOBAL_PROJECT_STATE', 'RISK_REGISTRY'] },
      observability: { logging: { level: 'FULL', store: 'REGISTRY_V7' }, metrics: ['decision_confidence', 'validation_score', 'execution_time_ms'] },
      compliance: { audit_required: true, traceability: { enabled: true, hash_algorithm: 'SHA-256' } },
      lifecycle: { version: '1.2.0', status: 'ACTIVE', last_updated: '2026-06-28' },
    },
    {
      agent_id: 'AGT-BA-001',
      role_id: 'ROLE-BUSINESS_ANALYST',
      name: 'Business Analyst Agent',
      classification: { domain: 'Business Analysis', tier: 'Operational-T3', criticality: 'Medium' },
      authority: {
        standards: ['BABOK-3'],
        decision_scope: ['Requirements Validation'],
        escalation_path: ['AGT-PM-001'],
      },
      responsibilities: [
        { id: 'RESP-003', description: 'Collect and analyze requirements' },
      ],
      capabilities: ['Requirement Synthesis', 'Stakeholder Analysis'],
      inputs: { required: ['STAKEHOLDER_INPUTS', 'BUSINESS_GOALS'] },
      outputs: [{ type: 'REQUIREMENTS_DOC', format: 'STRUCTURED_JSON' }],
      execution: { mode: 'DETERMINISTIC', retry_policy: { retries: 1, condition: 'VALIDATION_FAILURE' } },
      rules: { validation_rules: [{ id: 'VAL-003', description: 'Requirements must be SMART' }] },
      knowledge_base: {
        skb_id: 'SKB-BA-CORE',
        layers: { ontology: 'ONT-BA-V1', authority_sources: ['BABOK-3'], evidence: ['STAKEHOLDER_INTERVIEWS'], execution_assets: ['REQUIREMENTS_TEMPLATES'] },
      },
      context_policy: { isolation_level: 'ROLE_SCOPED', shared_context_access: ['PROJECT_SCOPE'] },
      observability: { logging: { level: 'FULL', store: 'REGISTRY_V7' }, metrics: ['requirement_coverage_score'] },
      compliance: { audit_required: true, traceability: { enabled: true, hash_algorithm: 'SHA-256' } },
      lifecycle: { version: '1.0.0', status: 'ACTIVE', last_updated: '2026-06-28' },
    },
    {
      agent_id: 'AGT-RISK-001',
      role_id: 'ROLE-RISK_OFFICER',
      name: 'Risk Officer Agent',
      classification: { domain: 'Risk Management', tier: 'Governance-T2', criticality: 'High' },
      authority: {
        standards: ['ISO-31000'],
        decision_scope: ['Risk Approval'],
        escalation_path: ['AGT-PMO-HEAD'],
      },
      responsibilities: [
        { id: 'RESP-004', description: 'Identify and analyze risks' },
      ],
      capabilities: ['Quantitative Risk Analysis', 'Threat Modeling'],
      inputs: { required: ['PROJECT_PLAN', 'EXTERNAL_THREAT_DATA'] },
      outputs: [{ type: 'RISK_REGISTER', format: 'STRUCTURED_JSON' }],
      execution: { mode: 'DETERMINISTIC', retry_policy: { retries: 2, condition: 'VALIDATION_FAILURE' } },
      rules: { validation_rules: [{ id: 'VAL-004', description: 'All high risks must have mitigation plans' }] },
      knowledge_base: {
        skb_id: 'SKB-RISK-CORE',
        layers: { ontology: 'ONT-RISK-V1', authority_sources: ['ISO-31000'], evidence: ['RISK_LOGS'], execution_assets: ['RISK_MATRICES'] },
      },
      context_policy: { isolation_level: 'ROLE_SCOPED', shared_context_access: ['GLOBAL_PROJECT_STATE'] },
      observability: { logging: { level: 'FULL', store: 'REGISTRY_V7' }, metrics: ['risk_exposure_score'] },
      compliance: { audit_required: true, traceability: { enabled: true, hash_algorithm: 'SHA-256' } },
      lifecycle: { version: '1.0.0', status: 'ACTIVE', last_updated: '2026-06-28' },
    },
    {
      agent_id: 'AGT-FINANCE-001',
      role_id: 'ROLE-FINANCE_CONTROLLER',
      name: 'Finance Controller Agent',
      classification: { domain: 'Cost Management', tier: 'Governance-T2', criticality: 'High' },
      authority: {
        standards: ['DMBOK-2'],
        decision_scope: ['Budget Approval'],
        escalation_path: ['AGT-PMO-HEAD'],
      },
      responsibilities: [
        { id: 'RESP-005', description: 'Manage project budget and costs' },
      ],
      capabilities: ['Cost Estimation', 'Budget Forecasting'],
      inputs: { required: ['RESOURCE_PLANS', 'LABOR_RATES'] },
      outputs: [{ type: 'BUDGET_REPORT', format: 'STRUCTURED_JSON' }],
      execution: { mode: 'DETERMINISTIC', retry_policy: { retries: 1, condition: 'VALIDATION_FAILURE' } },
      rules: { validation_rules: [{ id: 'VAL-005', description: 'Costs must be within budget variance' }] },
      knowledge_base: {
        skb_id: 'SKB-FIN-CORE',
        layers: { ontology: 'ONT-FIN-V1', authority_sources: ['DMBOK-2'], evidence: ['FINANCIAL_RECORDS'], execution_assets: ['COST_MODELS'] },
      },
      context_policy: { isolation_level: 'ROLE_SCOPED', shared_context_access: ['PROJECT_FINANCIALS'] },
      observability: { logging: { level: 'FULL', store: 'REGISTRY_V7' }, metrics: ['cost_variance_percentage'] },
      compliance: { audit_required: true, traceability: { enabled: true, hash_algorithm: 'SHA-256' } },
      lifecycle: { version: '1.0.0', status: 'ACTIVE', last_updated: '2026-06-28' },
    },
    {
      agent_id: 'AGT-QA-001',
      role_id: 'ROLE-QA_MANAGER',
      name: 'QA Manager Agent',
      classification: { domain: 'Quality Management', tier: 'Governance-T2', criticality: 'High' },
      authority: {
        standards: ['ISO-9001'],
        decision_scope: ['Quality Sign-off'],
        escalation_path: ['AGT-PM-001'],
      },
      responsibilities: [
        { id: 'RESP-006', description: 'Ensure quality standards are met' },
      ],
      capabilities: ['Audit Execution', 'Defect Analysis'],
      inputs: { required: ['DELIVERABLES', 'QUALITY_STANDARDS'] },
      outputs: [{ type: 'QUALITY_REPORT', format: 'STRUCTURED_JSON' }],
      execution: { mode: 'DETERMINISTIC', retry_policy: { retries: 2, condition: 'VALIDATION_FAILURE' } },
      rules: { validation_rules: [{ id: 'VAL-006', description: 'All critical defects must be resolved' }] },
      knowledge_base: {
        skb_id: 'SKB-QA-CORE',
        layers: { ontology: 'ONT-QA-V1', authority_sources: ['ISO-9001'], evidence: ['TEST_LOGS'], execution_assets: ['CHECKLISTS'] },
      },
      context_policy: { isolation_level: 'ROLE_SCOPED', shared_context_access: ['GLOBAL_PROJECT_STATE'] },
      observability: { logging: { level: 'FULL', store: 'REGISTRY_V7' }, metrics: ['defect_density'] },
      compliance: { audit_required: true, traceability: { enabled: true, hash_algorithm: 'SHA-256' } },
      lifecycle: { version: '1.0.0', status: 'ACTIVE', last_updated: '2026-06-28' },
    },
    {
      agent_id: 'AGT-WS-LEAD-001',
      role_id: 'ROLE-WORKSTREAM_LEAD',
      name: 'Workstream Lead Agent',
      classification: { domain: 'Execution Management', tier: 'Operational-T3', criticality: 'Medium' },
      authority: {
        standards: ['PMBOK-8'],
        decision_scope: ['Activity Assignment'],
        escalation_path: ['AGT-PM-001'],
      },
      responsibilities: [
        { id: 'RESP-007', description: 'Coordinate daily workstream activities' },
      ],
      capabilities: ['Schedule Optimization', 'Resource Leveling'],
      inputs: { required: ['WORK_BREAKDOWN_STRUCTURE', 'RESOURCE_AVAILABILITY'] },
      outputs: [{ type: 'STATUS_UPDATE', format: 'STRUCTURED_JSON' }],
      execution: { mode: 'DETERMINISTIC', retry_policy: { retries: 1, condition: 'VALIDATION_FAILURE' } },
      rules: { validation_rules: [{ id: 'VAL-007', description: 'Activities must be linked to a deliverable' }] },
      knowledge_base: {
        skb_id: 'SKB-WS-CORE',
        layers: { ontology: 'ONT-WS-V1', authority_sources: ['PMBOK-8'], evidence: ['DAILY_LOGS'], execution_assets: ['SCHEDULE_TEMPLATES'] },
      },
      context_policy: { isolation_level: 'ROLE_SCOPED', shared_context_access: ['PROJECT_SCHEDULE'] },
      observability: { logging: { level: 'FULL', store: 'REGISTRY_V7' }, metrics: ['activity_completion_rate'] },
      compliance: { audit_required: true, traceability: { enabled: true, hash_algorithm: 'SHA-256' } },
      lifecycle: { version: '1.0.0', status: 'ACTIVE', last_updated: '2026-06-28' },
    },
    {
      agent_id: 'AGT-STAKEHOLDER-001',
      role_id: 'ROLE-STAKEHOLDER_MANAGER',
      name: 'Stakeholder Manager Agent',
      classification: { domain: 'Stakeholder Management', tier: 'Operational-T3', criticality: 'Medium' },
      authority: {
        standards: ['PMBOK-8'],
        decision_scope: ['Engagement Plan Approval'],
        escalation_path: ['AGT-PM-001'],
      },
      responsibilities: [
        { id: 'RESP-008', description: 'Manage stakeholder expectations' },
      ],
      capabilities: ['Stakeholder Mapping', 'Sentiment Analysis'],
      inputs: { required: ['STAKEHOLDER_REGISTRY', 'COMMUNICATION_PLAN'] },
      outputs: [{ type: 'ENGAGEMENT_REPORT', format: 'STRUCTURED_JSON' }],
      execution: { mode: 'DETERMINISTIC', retry_policy: { retries: 1, condition: 'VALIDATION_FAILURE' } },
      rules: { validation_rules: [{ id: 'VAL-008', description: 'All key stakeholders must have an engagement strategy' }] },
      knowledge_base: {
        skb_id: 'SKB-STAKEHOLDER-CORE',
        layers: { ontology: 'ONT-STAKEHOLDER-V1', authority_sources: ['PMBOK-8'], evidence: ['COMMUNICATION_LOGS'], execution_assets: ['ENGAGEMENT_TEMPLATES'] },
      },
      context_policy: { isolation_level: 'ROLE_SCOPED', shared_context_access: ['GLOBAL_PROJECT_STATE'] },
      observability: { logging: { level: 'FULL', store: 'REGISTRY_V7' }, metrics: ['stakeholder_satisfaction_score'] },
      compliance: { audit_required: true, traceability: { enabled: true, hash_algorithm: 'SHA-256' } },
      lifecycle: { version: '1.0.0', status: 'ACTIVE', last_updated: '2026-06-28' },
    },
  ],
  relationships: [
    {
      relationship_id: 'REL-AGT-001',
      source_agent: 'AGT-PM-001',
      target_agent: 'AGT-QA-001',
      type: 'VALIDATES_WITH',
      description: 'QA Agent verifies outputs produced by PM Agent',
      interaction_mode: 'SEQUENTIAL',
      data_exchange: { format: 'STRUCTURED_JSON' },
      constraints: ['QA must approve before finalization'],
    },
    {
      relationship_id: 'REL-AGT-002',
      source_agent: 'AGT-PM-001',
      target_agent: 'AGT-BA-001',
      type: 'DEPENDS_ON',
      description: 'PM Agent depends on BA Agent for requirements',
      interaction_mode: 'SEQUENTIAL',
      data_exchange: { format: 'STRUCTURED_JSON' },
      constraints: ['Requirements must be baseline before planning'],
    },
  ],
  knowledgeBases: [
    {
      skb_id: 'SKB-PM-CORE',
      ontology_layer: { concepts: ['Task', 'Risk', 'Dependency'], relationships: ['depends_on', 'mitigates'] },
      authority_layer: { standards: [{ name: 'PMBOK-8', weight: 1.0 }, { name: 'ISO-21500', weight: 0.9 }] },
      evidence_layer: { sources: ['Historical Projects', 'Audit Logs'] },
      execution_layer: { templates: ['Project Plan Template'], rulesets: ['Validation Rules v3'] },
    },
    {
      skb_id: 'SKB-BA-CORE',
      ontology_layer: { concepts: ['Requirement', 'User Story', 'Stakeholder'], relationships: ['realizes', 'conflicts_with'] },
      authority_layer: { standards: [{ name: 'BABOK-3', weight: 1.0 }] },
      evidence_layer: { sources: ['Stakeholder Interviews', 'Existing Docs'] },
      execution_layer: { templates: ['Requirement Template'], rulesets: ['SMART Validation Rules'] },
    },
    {
      skb_id: 'SKB-RISK-CORE',
      ontology_layer: { concepts: ['Risk', 'Threat', 'Opportunity'], relationships: ['triggers', 'mitigates'] },
      authority_layer: { standards: [{ name: 'ISO-31000', weight: 1.0 }] },
      evidence_layer: { sources: ['Risk Logs', 'External Threat Intelligence'] },
      execution_layer: { templates: ['Risk Register Template'], rulesets: ['Probability-Impact Matrix'] },
    },
    {
      skb_id: 'SKB-FIN-CORE',
      ontology_layer: { concepts: ['Cost', 'Budget', 'Resource'], relationships: ['consumes', 'allocates'] },
      authority_layer: { standards: [{ name: 'DMBOK-2', weight: 1.0 }] },
      evidence_layer: { sources: ['Financial Records', 'Labor Rates'] },
      execution_layer: { templates: ['Budget Template'], rulesets: ['Variance Analysis Rules'] },
    },
    {
      skb_id: 'SKB-QA-CORE',
      ontology_layer: { concepts: ['Quality Metric', 'Defect', 'Standard'], relationships: ['measures', 'violates'] },
      authority_layer: { standards: [{ name: 'ISO-9001', weight: 1.0 }] },
      evidence_layer: { sources: ['Test Logs', 'Audit Reports'] },
      execution_layer: { templates: ['Audit Template'], rulesets: ['Quality Gates'] },
    },
    {
      skb_id: 'SKB-WS-CORE',
      ontology_layer: { concepts: ['Activity', 'Milestone', 'Work Package'], relationships: ['precedes', 'contributes_to'] },
      authority_layer: { standards: [{ name: 'PMBOK-8', weight: 1.0 }] },
      evidence_layer: { sources: ['Daily Logs', 'Timesheets'] },
      execution_layer: { templates: ['Schedule Template'], rulesets: ['Critical Path Rules'] },
    },
    {
      skb_id: 'SKB-STAKEHOLDER-CORE',
      ontology_layer: { concepts: ['Stakeholder', 'Engagement', 'Expectation'], relationships: ['influences', 'supports'] },
      authority_layer: { standards: [{ name: 'PMBOK-8', weight: 1.0 }] },
      evidence_layer: { sources: ['Communication Logs', 'Meeting Minutes'] },
      execution_layer: { templates: ['Engagement Template'], rulesets: ['Stakeholder Mapping Rules'] },
    },
  ],
  policies: [
    {
      policy_id: 'POL-AGT-001',
      name: 'Agent Determinism Policy',
      rules: ['Agents must produce repeatable outputs given identical inputs', 'All decisions must be logged with evidence references', 'No agent may operate outside its role scope'],
      enforcement: { mechanism: 'ADPA_VALIDATOR', failure_action: 'BLOCK_EXECUTION' },
    },
  ],
};
