#!/usr/bin/env ts-node

/**
 * Test script for Confluence publishing integration
 * Tests the document generation hook and Confluence publishing job
 */

import { pool } from '../src/database/connection'
import { addJob } from '../src/services/queueService'
import { logger } from '../src/utils/logger'
import { v4 as uuidv4 } from 'uuid'

async function testConfluencePublishing() {
  try {
    logger.info('Starting Confluence publishing test...')

    // Test data
    const testProjectId = uuidv4()
    const testDocumentId = uuidv4()
    const testUserId = uuidv4()
    const testTitle = 'Test Document - Confluence Publishing'
    const testMarkdown = `# Test Document

This is a test document generated to verify the Confluence publishing integration.

## Features Tested

- Document generation hook
- Confluence publishing job
- Project mapping validation
- Markdown content publishing
- URL storage in document metadata

## Test Details

- Project ID: ${testProjectId}
- Document ID: ${testDocumentId}
- Generated at: ${new Date().toISOString()}

## Content

This document contains various markdown elements to test the conversion:

### Lists

- Item 1
- Item 2
- Item 3

### Code Block

\`\`\`javascript
console.log('Hello, Confluence!')
\`\`\`

### Table

| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
| Value 1  | Value 2  | Value 3  |
| Value 4  | Value 5  | Value 6  |

### Links

[ADPA Platform](https://adpa.example.com)

---

*Generated by ADPA Document Generation Test*
`

    // Create test project integration (simulate a project with Confluence mapping)
    const testSpaceKey = process.env.TEST_CONFLUENCE_SPACE_KEY || 'TEST'
    
    logger.info('Creating test project integration...', {
      projectId: testProjectId,
      spaceKey: testSpaceKey
    })

    await pool.query(`
      INSERT INTO project_integrations (project_id, confluence_space_key)
      VALUES ($1, $2)
      ON CONFLICT (project_id) DO UPDATE SET
        confluence_space_key = EXCLUDED.confluence_space_key,
        updated_at = now()
    `, [testProjectId, testSpaceKey])

    // Enqueue Confluence publishing job
    logger.info('Enqueuing Confluence publishing job...')
    
    const jobId = await addJob(
      'confluence-publishing',
      'publish-to-confluence',
      {
        jobId: uuidv4(),
        userId: testUserId,
        documentId: testDocumentId,
        projectId: testProjectId,
        title: testTitle,
        markdown: testMarkdown
      },
      {
        attempts: 3,
        backoff: {
          type: 'exponential',
          delay: 2000
        },
        timeout: 120000 // 2 minutes
      }
    )

    logger.info(`Confluence publishing job enqueued successfully!`, {
      jobId,
      projectId: testProjectId,
      title: testTitle
    })

    logger.info('Test completed. Check the job queue for processing status.')
    logger.info('If Confluence credentials are configured, the document should be published to the test space.')

    // Clean up test data
    logger.info('Cleaning up test data...')
    await pool.query('DELETE FROM project_integrations WHERE project_id = $1', [testProjectId])

  } catch (error) {
    logger.error('Confluence publishing test failed:', error)
    throw error
  }
}

// Run the test
if (require.main === module) {
  testConfluencePublishing()
    .then(() => {
      logger.info('Test completed successfully')
      process.exit(0)
    })
    .catch((error) => {
      logger.error('Test failed:', error)
      process.exit(1)
    })
}

export { testConfluencePublishing }